# Generated by Django 5.1.15 on 2026-07-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='annotations/images/%Y/%m/%d/'),
        ),
    ]
