# Generated by Django 5.1.15 on 2026-07-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='frame_time',
            field=models.FloatField(blank=True, help_text='Video timestamp in seconds when this annotation was drawn. Null for image annotations.', null=True),
        ),
    ]
