# Generated by Django 5.1.15 on 2026-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_imageset_image_image_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
